const menuList = [
  {
    image: "/menu/menu1.jpg",
    images: [
      "/menu/menu1.jpg",
      "/menu/menu1-1.jpg",
      "/menu/menu1-2.jpg",
      "/menu/menu1-3.jpg",
      "/menu/menu1-4.jpg",
    ],
    alt: "Pork Slice Marinasi",
    title: "Pork Slice Marinasi 500gr",
    price: "Rp70.000",
    variants: [
      "BBQ",
      "BLACKPEPPER",
      "TERIYAKI",
      "BUMBU BALI PEDAS MANIS",
      "BULGOGI",
    ],
  },
  {
    image: "/menu/menu5.JPG",
    images: ["/menu/menu5.JPG", "/menu/menu6.png", "/menu/menu6-3.png"],
    alt: "Urutan Babi",
    title: "Urutan Asap & urutan majemuh",
    price: "Rp77.500",
    variants: ["Urutan Majemuh", "Urutan Asap Smoky", "Urutan Goreng"],
  },
  {
    image: "/menu/menu2.jpg",
    images: ["/menu/menu2.jpg", "/menu/menu2-3.png"],
    alt: "Chicken & Pork Bacon",
    title: "Bacon Selection (500gr)",
    price: "Klik untuk lihat varian harga",
    variants: [
      "Streaky pork bacon - Rp57.000 ",
      "Chicken bacon rasher - Rp70.000",
      "Pork bacon slice - Rp94.000",
    ],
  },
  {
    image: "/menu/menu3.jpg",
    images: ["/menu/menu3.jpg"],
    alt: "Samsam Guling",
    title: "Samsam Guling",
    price: "Rp85.000 - Rp160.000",
    variants: ["mini", "jumbo"],
  },
  {
    image: "/menu/menu4.jpg",
    images: ["/menu/menu4.jpg", "/menu/menu4-2.jpg"],
    alt: "Samcam Kum",
    title: "Samcam Kum 500gr",
    price: "Rp72.500",
    variants: ["-"],
  },
  {
    image: "/menu/menu5-2.jpg",
    images: ["/menu/menu5-2.jpg", "/menu/menu5-3.jpg"],
    alt: "Urutan Ayam",
    title: "Urutan Biasa & Urutan Asap",
    price: "Rp70.000 - Rp.75.000",
    variants: ["Urutan biasa", "urutan asap"],
  },
  {
    image: "/menu/menu7-2.png",
    images: ["/menu/menu7-2.png", "/menu/menu7.png"],
    alt: "Dendeng Babi",
    title: "Dendeng Babi Asap Sambal Kecombrang",
    price: "Rp 75.000",
    variants: ["-"],
  },
  {
    image: "/menu/menu8.jpg",
    images: ["/menu/menu8.jpg"],
    alt: "Lapchiong",
    title: "Lapchiong",
    price: "Rp75.000 - Rp86.000",
    variants: ["Lapchiong BB 500gr", "Lapchiong Ayam 500gr"],
  },
  {
    image: "/menu/menu9.jpg",
    images: ["/menu/menu9.jpg", "/menu/menu9-2.jpg"],
    alt: "Bakso",
    title: "Bakso",
    price: "Rp53.000 - Rp58.000",
    variants: ["Bakso Ayam", "Bakso Babi"],
  },
  {
    image: "/menu/menu10.png",
    images: ["/menu/menu10-2.jpg", "/menu/menu10.png"],
    alt: "Sosis",
    title: "Sosis",
    price: "Rp54.000 - Rp58.000",
    variants: ["Sosis Ayam", "Sosis Babi"],
  },
  {
    image: "/menu/menu11.png",
    images: ["/menu/menu11.png", "/menu/menu11-2.png"],
    alt: "Babi Goreng Daun Jeruk",
    title: "Babi Goreng Daun Jeruk",
    price: "Rp70.000",
    variants: ["-"],
  },
  {
    image: "/menu/menu12.jpg",
    images: ["/menu/menu12.jpg"],
    alt: "Babi Kumkum",
    title: "Babi Kumkum",
    price: "Rp70.000",
    variants: ["-"],
  },
];

export default menuList;
